// NES Games Database - 44 Classic Games (with ROMs)
const gamesDatabase = [
{
        id: 1,
        title: "超级马里奥兄弟",
        titleEn: "Super Mario Bros",
        year: 1985,
        publisher: "Nintendo",
        genre: "action",
        rating: 5.0,
        description: "任天堂的招牌动作游戏，玩家控制马里奥在蘑菇王国中冒险，拯救碧奇公主。",
        icon: "fa-user-astronaut",
        color: "#E60012"
    },
{
        id: 2,
        title: "塞尔达传说",
        titleEn: "The Legend of Zelda",
        year: 1986,
        publisher: "Nintendo",
        genre: "adventure",
        rating: 5.0,
        description: "开创性的动作冒险游戏，林克在海拉尔大陆上收集三角神力，拯救塞尔达公主。",
        icon: "fa-dragon",
        color: "#32CD32"
    },
{
        id: 3,
        title: "魂斗罗",
        titleEn: "Contra",
        year: 1987,
        publisher: "Konami",
        genre: "shooter",
        rating: 4.8,
        description: "经典的横向卷轴射击游戏，两名精英士兵对抗外星入侵者。",
        icon: "fa-crosshairs",
        color: "#FF4500"
    },
{
        id: 4,
        title: "坦克大战",
        titleEn: "Tank Battle",
        year: 1985,
        publisher: "Namco",
        genre: "action",
        rating: 4.7,
        description: "战略坦克战斗游戏，保卫基地同时消灭敌方坦克。",
        icon: "fa-tank",
        color: "#4169E1"
    },
{
        id: 5,
        title: "吃豆人",
        titleEn: "Pac-Man",
        year: 1980,
        publisher: "Namco",
        genre: "puzzle",
        rating: 4.6,
        description: "经典街机游戏，控制吃豆人在迷宫中吃掉所有豆子，同时躲避幽灵。",
        icon: "fa-circle",
        color: "#FFFF00"
    },
{
        id: 6,
        title: "大金刚",
        titleEn: "Donkey Kong",
        year: 1981,
        publisher: "Nintendo",
        genre: "action",
        rating: 4.5,
        description: "马里奥的首次登场，从大金刚手中救出宝琳。",
        icon: "fa-paw",
        color: "#8B4513"
    },
{
        id: 7,
        title: "洛克人",
        titleEn: "Mega Man",
        year: 1987,
        publisher: "Capcom",
        genre: "action",
        rating: 4.8,
        description: "机器人洛克人对抗邪恶博士威利，收集对手武器。",
        icon: "fa-robot",
        color: "#00BFFF"
    },
{
        id: 8,
        title: "恶魔城",
        titleEn: "Castlevania",
        year: 1986,
        publisher: "Konami",
        genre: "action",
        rating: 4.7,
        description: "哥特式恐怖动作游戏，西蒙·贝尔蒙特对抗德古拉伯爵。",
        icon: "fa-hat-wizard",
        color: "#4B0082"
    },
{
        id: 9,
        title: "银河战士",
        titleEn: "Metroid",
        year: 1986,
        publisher: "Nintendo",
        genre: "adventure",
        rating: 4.9,
        description: "科幻冒险游戏，萨姆斯·阿兰在行星泽贝斯上对抗太空海盗。",
        icon: "fa-space-shuttle",
        color: "#006400"
    },
{
        id: 10,
        title: "忍者龙剑传",
        titleEn: "Ninja Gaiden",
        year: 1988,
        publisher: "Tecmo",
        genre: "action",
        rating: 4.7,
        description: "快节奏忍者动作游戏，隼龙为父报仇。",
        icon: "fa-user-ninja",
        color: "#2F4F4F"
    },
{
        id: 11,
        title: "俄罗斯方块",
        titleEn: "Tetris",
        year: 1989,
        publisher: "Nintendo",
        genre: "puzzle",
        rating: 4.9,
        description: "经典的益智游戏，堆叠俄罗斯方块以消除行。",
        icon: "fa-cube",
        color: "#FF1493"
    },
{
        id: 12,
        title: "炸弹人",
        titleEn: "Bomberman",
        year: 1985,
        publisher: "Hudson Soft",
        genre: "action",
        rating: 4.5,
        description: "策略动作游戏，放置炸弹炸毁障碍物和敌人。",
        icon: "fa-bomb",
        color: "#FF6347"
    },
{
        id: 13,
        title: "冰山登山者",
        titleEn: "Ice Climber",
        year: 1985,
        publisher: "Nintendo",
        genre: "action",
        rating: 4.3,
        description: "攀爬冰山，击退敌人，到达山顶。",
        icon: "fa-mountain",
        color: "#00CED1"
    },
{
        id: 14,
        title: "打鸭子",
        titleEn: "Duck Hunt",
        year: 1984,
        publisher: "Nintendo",
        genre: "shooter",
        rating: 4.4,
        description: "使用光枪射击飞过的鸭子，经典射击游戏。",
        icon: "fa-feather",
        color: "#FFD700"
    },
{
        id: 15,
        title: "拳无虚发",
        titleEn: "Punch-Out!!",
        year: 1987,
        publisher: "Nintendo",
        genre: "sports",
        rating: 4.8,
        description: "拳击游戏，小路易攀登拳击世界冠军之路。",
        icon: "fa-fist-raised",
        color: "#DC143C"
    },
{
        id: 16,
        title: "最终幻想",
        titleEn: "Final Fantasy",
        year: 1987,
        publisher: "Square",
        genre: "rpg",
        rating: 4.9,
        description: "开创性的JRPG，四位光之战士拯救世界。",
        icon: "fa-helmet-battle",
        color: "#1E90FF"
    },
{
        id: 17,
        title: "勇者斗恶龙",
        titleEn: "Dragon Quest",
        year: 1986,
        publisher: "Enix",
        genre: "rpg",
        rating: 4.8,
        description: "日本国民级RPG，勇者罗德拯救阿雷夫加德王国。",
        icon: "fa-shield-alt",
        color: "#4169E1"
    },
{
        id: 18,
        title: "星之卡比",
        titleEn: "Kirby's Adventure",
        year: 1993,
        publisher: "Nintendo",
        genre: "action",
        rating: 4.7,
        description: "粉红英雄卡比吞噬敌人并复制他们的能力。",
        icon: "fa-star",
        color: "#FF69B4"
    },
{
        id: 19,
        title: "马里奥兄弟3",
        titleEn: "Super Mario Bros 3",
        year: 1988,
        publisher: "Nintendo",
        genre: "action",
        rating: 5.0,
        description: "马里奥系列的巅峰之作，引入狸猫装等众多新元素。",
        icon: "fa-leaf",
        color: "#228B22"
    },
{
        id: 20,
        title: "合金装备",
        titleEn: "Metal Gear",
        year: 1987,
        publisher: "Konami",
        genre: "adventure",
        rating: 4.6,
        description: "潜行游戏先驱，蛇潜入外要塞摧毁核武器。",
        icon: "fa-mask",
        color: "#2F4F4F"
    },
{
        id: 21,
        title: "双截龙",
        titleEn: "Double Dragon",
        year: 1987,
        publisher: "Technos",
        genre: "action",
        rating: 4.5,
        description: "经典的横向卷轴清版游戏，李氏兄弟救出玛丽安。",
        icon: "fa-users",
        color: "#8B0000"
    },
{
        id: 23,
        title: "赤影战士",
        titleEn: "Shadow of the Ninja",
        year: 1990,
        publisher: "Natsume",
        genre: "action",
        rating: 4.6,
        description: "双人忍者合作游戏，对抗邪恶幕府将军。",
        icon: "fa-user-secret",
        color: "#000080"
    },
{
        id: 24,
        title: "绿色兵团",
        titleEn: "Rush'n Attack",
        year: 1987,
        publisher: "Konami",
        genre: "action",
        rating: 4.3,
        description: "单人潜入敌营，消灭敌人并营救俘虏。",
        icon: "fa-running",
        color: "#556B2F"
    },
{
        id: 25,
        title: "淘金者",
        titleEn: "Lode Runner",
        year: 1983,
        publisher: "Broderbund",
        genre: "puzzle",
        rating: 4.5,
        description: "策略益智游戏，收集所有黄金并逃离。",
        icon: "fa-coins",
        color: "#DAA520"
    },
{
        id: 26,
        title: "所罗门之钥",
        titleEn: "Solomon's Key",
        year: 1986,
        publisher: "Tecmo",
        genre: "puzzle",
        rating: 4.4,
        description: "解谜平台游戏，创造和破坏方块以找到钥匙。",
        icon: "fa-key",
        color: "#9400D3"
    },
{
        id: 27,
        title: "泡泡龙",
        titleEn: "Bubble Bobble",
        year: 1986,
        publisher: "Taito",
        genre: "action",
        rating: 4.6,
        description: "可爱风格平台游戏，恐龙兄弟用泡泡困住敌人。",
        icon: "fa-soap",
        color: "#00CED1"
    },
{
        id: 29,
        title: "影之传说",
        titleEn: "The Legend of Kage",
        year: 1985,
        publisher: "Taito",
        genre: "action",
        rating: 4.4,
        description: "忍者影救出被绑架的公主，对抗邪恶组织。",
        icon: "fa-moon",
        color: "#191970"
    },
{
        id: 31,
        title: "马里奥高尔夫",
        titleEn: "Mario Golf",
        year: 1991,
        publisher: "Nintendo",
        genre: "sports",
        rating: 4.5,
        description: "马里奥世界的高尔夫游戏，简单易上手。",
        icon: "fa-golf-ball",
        color: "#228B22"
    },
{
        id: 33,
        title: "越野机车",
        titleEn: "Excitebike",
        year: 1984,
        publisher: "Nintendo",
        genre: "sports",
        rating: 4.3,
        description: "摩托越野比赛，创建自定义赛道。",
        icon: "fa-motorcycle",
        color: "#8B4513"
    },
{
        id: 35,
        title: "世界杯",
        titleEn: "World Cup",
        year: 1988,
        publisher: "Nintendo",
        genre: "sports",
        rating: 4.3,
        description: "足球比赛游戏，带领国家队赢得世界杯。",
        icon: "fa-futbol",
        color: "#006400"
    },
{
        id: 36,
        title: "墨",
        titleEn: "Tecmo Bowl",
        year: 1989,
        publisher: "Tecmo",
        genre: "sports",
        rating: 4.4,
        description: "美式足球游戏，简单的操作和激烈的比赛。",
        icon: "fa-football-ball",
        color: "#8B0000"
    },
{
        id: 37,
        title: "弹珠台",
        titleEn: "Pinball",
        year: 1984,
        publisher: "Nintendo",
        genre: "action",
        rating: 4.2,
        description: "经典弹珠台游戏，马里奥主题的弹珠台。",
        icon: "fa-bowling-ball",
        color: "#C0C0C0"
    },
{
        id: 38,
        title: "气球塔防",
        titleEn: "Balloon Fight",
        year: 1984,
        publisher: "Nintendo",
        genre: "action",
        rating: 4.3,
        description: "控制角色在气球间跳跃，击败敌人。",
        icon: "fa-cloud",
        color: "#87CEEB"
    },
{
        id: 39,
        title: "西天取经",
        titleEn: "Journey to the West",
        year: 1988,
        publisher: "Namco",
        genre: "action",
        rating: 4.4,
        description: "基于西游记的动作游戏，孙悟空的冒险。",
        icon: "fa-bolt",
        color: "#FFD700"
    },
{
        id: 41,
        title: "火之鸟",
        titleEn: "Phoenix",
        year: 1987,
        publisher: "Sega",
        genre: "shooter",
        rating: 4.4,
        description: "纵向卷轴射击游戏，操控火鸟对抗敌人。",
        icon: "fa-fire",
        color: "#FF4500"
    },
{
        id: 42,
        title: "小蜜蜂",
        titleEn: "Galaga",
        year: 1981,
        publisher: "Namco",
        genre: "shooter",
        rating: 4.5,
        description: "经典太空射击游戏，击落外星昆虫。",
        icon: "fa-rocket",
        color: "#0000CD"
    },
{
        id: 43,
        title: "太空侵略者",
        titleEn: "Space Invaders",
        year: 1985,
        publisher: "Taito",
        genre: "shooter",
        rating: 4.4,
        description: "射击游戏的鼻祖，消灭外星入侵者。",
        icon: "fa-meteor",
        color: "#00FF00"
    },
{
        id: 44,
        title: "1942",
        titleEn: "1942",
        year: 1984,
        publisher: "Capcom",
        genre: "shooter",
        rating: 4.5,
        description: "二战背景的纵向射击游戏，驾驶战机对抗敌军。",
        icon: "fa-fighter-jet",
        color: "#1E90FF"
    },
{
        id: 45,
        title: "吸尘器",
        titleEn: "Wrecking Crew",
        year: 1985,
        publisher: "Nintendo",
        genre: "puzzle",
        rating: 4.3,
        description: "马里奥和路易吉拆毁建筑物的益智游戏。",
        icon: "fa-hammer",
        color: "#CD853F"
    },
{
        id: 46,
        title: "石匠",
        titleEn: "Mario Bros",
        year: 1983,
        publisher: "Nintendo",
        genre: "action",
        rating: 4.4,
        description: "马里奥系列首作，消灭管道中的害虫。",
        icon: "fa-bug",
        color: "#228B22"
    },
{
        id: 48,
        title: "功夫",
        titleEn: "Kung Fu",
        year: 1984,
        publisher: "Nintendo",
        genre: "action",
        rating: 4.4,
        description: "李的功夫之旅，救出被绑架的女友。",
        icon: "fa-hand-rock",
        color: "#8B0000"
    },
{
        id: 49,
        title: "猪小弟",
        titleEn: "Pooyan",
        year: 1982,
        publisher: "Konami",
        genre: "action",
        rating: 4.2,
        description: "可爱射击游戏，保护小猪免受狼群袭击。",
        icon: "fa-piggy-bank",
        color: "#FFC0CB"
    },
{
        id: 50,
        title: "大蜜蜂",
        titleEn: "Xevious",
        year: 1982,
        publisher: "Namco",
        genre: "shooter",
        rating: 4.5,
        description: "革命性的射击游戏，同时攻击空中和地面敌人。",
        icon: "fa-plane",
        color: "#4169E1"
    },
{
        id: 51,
        title: "高桥名人的冒险岛",
        titleEn: "Adventure Island",
        year: 1986,
        publisher: "Hudson Soft",
        genre: "action",
        rating: 4.6,
        description: "高桥名人在岛上冒险，收集水果并击败恐龙。",
        icon: "fa-island-tropical",
        color: "#228B22"
    }
];

const genreNames = {
    action: "动作",
    adventure: "冒险",
    shooter: "射击",
    puzzle: "益智",
    sports: "运动",
    rpg: "角色扮演"
};
